### ISSUE TITLE
parser: Test fixtures?

### ISSUE THREAD

**Issue by fusetim** [fluent4s/fluent4s#4]
Fluent syntax is complex and needs a lot of tests to be sure it follows the specs. 
As parts of their testing setup, the other fluent implementations uses Fixtures which are Fluent Resources as files and their corresponding AST as JSON files. It allows us to test a set of features easily.

We might need to consider implementing a way to transform our AST as a JSON file to make possible the uses of Fixtures.

Where fixtures exists?
- [fluent-rs](https://github.com/projectfluent/fluent-rs/tree/master/fluent-syntax/tests/fixtures)
- [fluent-kotlin](https://github.com/projectfluent/fluent-kotlin/tree/master/fluent.syntax/src/test/resources)
- [fluent-js](https://github.com/projectfluent/fluent/tree/185a02908e8ce0d66f5234cd3f501fa1bfa8824e/test/fixtures)
- [python-fluent](https://github.com/projectfluent/python-fluent/tree/7b73fde73e67e48ad7d68289f7f28d4fd9f7e202/fluent.syntax/tests/syntax)

**Comment by fusetim** [comment]
### TODO List
* Parsing errors : 
  - [x] Junk nightmare and error recovery ( b0e963ba1c26506f4962f44c3b07ff2ab7b91bb6 )
  - [x] Multiline literal. ( 3c55e2b47ec6283ed39ca4ff4f9831ea60bd6c99 )
  - [ ] Parse entries 
  - [ ] Missing line end after variant list.
        -> delayed, breaks lots of things
* Validation errors:
  - [ ] Function identifier can not use lowercase characters. ( 3c55e2b47ec6283ed39ca4ff4f9831ea60bd6c99 )
        -> Need fix, break when using number and symbols 
  - [x] Positional arg must not follow keyword args. ( 3c55e2b47ec6283ed39ca4ff4f9831ea60bd6c99 )
  - [x] Named arguments must be unique. ( 3c55e2b47ec6283ed39ca4ff4f9831ea60bd6c99 )
  - [x] Messages cannot be parameterized. ( 3c55e2b47ec6283ed39ca4ff4f9831ea60bd6c99 )
  - [x] Equivalent to a MessageReference callee. ( 3c55e2b47ec6283ed39ca4ff4f9831ea60bd6c99 )
  - [x] Term attributes may not be used in Placeables. ( 3c55e2b47ec6283ed39ca4ff4f9831ea60bd6c99 )
  - [x] Variables cannot be parameterized. ( a32730a79f36de91052aa179d0313469bf73aa50 )
  - [x] Term attributes may not be used for interpolation. ( a32730a79f36de91052aa179d0313469bf73aa50 )
  - [ ] Function references are invalid outside of call expression. 
         -> delayed, difficult to implement, specification rather unclear on Message identifier format, what exacly is a call expression?
  - [x] CallExpressions on Terms are similar to TermReferences. ( a32730a79f36de91052aa179d0313469bf73aa50 )
  - [x] Message values may not be used as selectors. ( a32730a79f36de91052aa179d0313469bf73aa50)
  - [x] Message attributes may not be used as selectors. ( a32730a79f36de91052aa179d0313469bf73aa50 )
  - [x] Term values may not be used as selectors. ( a32730a79f36de91052aa179d0313469bf73aa50 )
  - [x] Nested expressions are not valid selectors. ( a32730a79f36de91052aa179d0313469bf73aa50 )
  - [x] Select expressions are not valid selectors. ( a32730a79f36de91052aa179d0313469bf73aa50 )
  - [ ] Make invalid nested PlaceableExpr in Placeable
